services:
  frontend:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    pull_policy: build
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.door3.entrypoints=http"
      - "traefik.http.routers.door3.rule=Host(`door3.test.pep-digital.de`)"
      - "traefik.http.middlewares.door3-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.door3.middlewares=door-https-redirect"
      - "traefik.http.routers.door3-secure.entrypoints=https"
      - "traefik.http.routers.door3-secure.rule=Host(`door3.test.pep-digital.de`)"
      - "traefik.http.routers.door3-secure.tls=true"
      - "traefik.http.routers.door3-secure.tls.certresolver=http"
      - "traefik.http.routers.door3-secure.service=door3"
      - "traefik.http.services.door3.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true